# NOTE: this deployment works with the "toolforge" Kubernetes cluster, and not the legacy "default" cluster.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rlutsbot.bot
  namespace: tool-rluts
  labels:
    name: rlutsbot.bot
    # The toolforge=tool label will cause $HOME and other paths to be mounted from Toolforge
    toolforge: tool
spec:
  replicas: 1
  selector:
    matchLabels:
      name: rlutsbot.bot
      toolforge: tool
  template:
    metadata:
      labels:
        name: rlutsbot.bot
        toolforge: tool
    spec:
      containers:
        - name: bot
          image: docker-registry.tools.wmflabs.org/toolforge-python39-sssd-base:latest
          command: [ "sleep", "infinity" ]
          workingDir: /data/project/rluts/statistic_bot
          env:
            - name: HOME
              value: /data/project/rluts
          imagePullPolicy: Always